plugins:
  - serverless-domain-manager

service: samples-custom-domain

custom:
  customDomain:
    domainName: serverless-samples.leanstacks.net
    basePath: ''
    certificateName: '*.leanstacks.net'
    stage: ${self:custom.stage}
    createRoute53Record: true
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: /hello
          method: get
  goodbye:
    handler: index.handler
    events:
      - http:
          path: /goodbye
          method: get
