service: samples-environment-ssm

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  memorySize: 128
  environment:
    GREETING_AUDIENCE: ${ssm:/${self:service}/${self:custom.stage}/greeting-audience}

functions:
  hello:
    handler: index.handler
    environment:
      GREETING_PREFIX: 'Hello'
    events:
      - http:
          path: /hello
          method: get
  goodbye:
    handler: index.handler
    environment:
      GREETING_PREFIX: 'Goodbye'
    events:
      - http:
          path: /goodbye
          method: get
