service: samples-custom-domain-products

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: 'products'
    certificateName: '*.leanstacks.net'
    stage: ${self:custom.stage}
    createRoute53Record: true
  domains:
    dev: serverless-samples-dev.leanstacks.net
    prod: serverless-samples.leanstacks.net
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  getProducts:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
