##
# The "messages" service project defines the functions and API endpoints for 
#  a REST "messages" resource.
# Rather than deploying an entirely new API within API Gateway, the messages 
#  endpoints will be created within the API whose identifer was exported from 
#  the "api" project.
##
service: samples-shared-api-messages

custom:
  apiStackName: samples-shared-api-base   # The CloudFormation stack name (minus stage) where the API is created.
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
  apiGateway:   # Specify the API to which HTTP endpoints are attached. Reference the Outputs from the API project.
    restApiId: ${cf:${self:custom.apiStackName}-${self:custom.stage}.RestApiId}
    restApiRootResourceId: ${cf:${self:custom.apiStackName}-${self:custom.stage}.RestApiRootResourceId}

functions:
  listMessages:
    handler: index.handler
    events:
      - http: 
          path: /messages
          method: get
  getMessage:
    handler: index.handler
    events:
      - http: 
          path: /messages/{proxy+}
          method: get
