service: samples-step-functions

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  createMessage:
    handler: index.createMessage
  toUppercase:
    handler: index.toUppercase

stepFunctions:
  stateMachines:
    createMessage:
      name: ${self:service}-${self:custom.stage}-createMessage
      events:
        - http:
            path: /messages
            method: POST
      definition:
        Comment: A sample state machine that creates a Hello World message and converts it to uppercase.
        StartAt: CreateMessage
        States:
          CreateMessage:
            Type: Task
            Resource:
              Fn::GetAtt: [createMessage, Arn] # reference function in this file
            Next: ToUppercase
          ToUppercase:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:custom.stage}-toUppercase" # build reference to function in this file or external
            End: true
